loan_app/urls.py
from django.contrib import admin
from django.urls import path
from .import views

app_name = "loan_app"
urlpatterns = [
  path('/', admin.site.urls),
  path("",views.home,name="home"),
  path("bank_admin/",views.bank_admin,name="bank_admin"),
  path("apply/",views.apply,name="apply"),  
  path("details/",views.details,name="details"),  
  path("verification/",views.verification,name="verification"),  
  path("getresult/",views.getresult,name="getresult"),
  path("getresult_admin/",views.getresult_admin,name="getresult_admin"), 
  path("login/",views.login_page,name="login_page"), 
  path("logout/", views.logout_request, name="logout_request"),
  path("terms/", views.terms, name="terms"),
  path("loan_agreement/", views.loan_agreement, name="loan_agreement"),
  path("loan_tips/", views.loan_tips, name="loan_tips"),
  path("howitworks/", views.howitworks, name="howitworks"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
  path('admin/', admin.site.urls),
  path("", include("loan_app.urls")),  
]

loan_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import pre_save
from django.conf import settings
from django.db.models.manager import Manager
from django.contrib.auth import authenticate

# Create your models here.
#Customer model
User = settings.AUTH_USER_MODEL
class CustomerProfile(models.Model):
    national_id=models.CharField(max_length=13)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    age=models.IntegerField(default=18)
    income=models.IntegerField(default=3000)
    num_unsecured_l_term_all = models.IntegerField(default = 1)
    num_loan_payments_missed = models.IntegerField(default = 0)
    num_debit_orders_bounced = models.IntegerField(default = 3)
    wknd_shopper_flag = models.BooleanField(default=False)
    salary_indicator = models.BooleanField(default=True)
    num_credit_transactions = models.IntegerField(default = 12)
    house_credit_score = models.IntegerField(default = 0)
    num_properties_owned = models.IntegerField(default = 0)
    
    def __str__(self):
        return self.user.first_name

class Decision(models.Model):
    decision=models.BooleanField(default=False)
    refnum=models.CharField(max_length=13)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    amount=models.IntegerField()
    term_months=models.IntegerField()

loan_app/forms.py
from django import forms
from django import forms
from django.core.exceptions import ValidationError
from django.forms.widgets import PasswordInput
from django.contrib.auth import get_user_model



User = get_user_model()
class loginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
        'class':'form-control',
        'placeholder':'Username',
        'required':'required'
        }
    ))
    password = forms.CharField(widget= forms.PasswordInput( attrs={
        'class':'form-control',
        'placeholder':'Password',
        'required':'required'
        }))

class registerForm(forms.Form):
    
    username = forms.CharField(widget=forms.TextInput(
        attrs={
        'class':'form-control',
        'placeholder':'Username',
        'required':'required'
        }
    ))

    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
        'class':'form-control',
        'placeholder':'First name',
        'required':'required'
        }
    ))

    last_name = forms.CharField(widget=forms.TextInput(
      attrs={
        'class':'form-control',
        'placeholder':'Last name',
        'required':'required'
        }
    ))

    password = forms.CharField(widget = forms.PasswordInput( 
      attrs={
        'class':'form-control',
        'placeholder':'Password',
        'required':'required'
        }
    ))

    conf_password = forms.CharField(label = "Confirm password",widget = forms.PasswordInput( 
      attrs={
        'class':'form-control',
        'placeholder':'Confirm Password',
        'required':'required'
        }
    ))
    email = forms.EmailField(widget=forms.TextInput(
        attrs={
        'class':'form-control',
        'placeholder':'Email',
        'required':'required',
        'type':'email'
        }
    ))

    def clean_username(self):
        username = self.cleaned_data.get("username")
        qs = User.objects.filter(username= username)
        if qs.exists():
            raise forms.ValidationError("Username already exists")
        return username

    def clean_email(self):
        email = self.cleaned_data.get("email")
        qs = User.objects.filter(email = email)
        if qs.exists():
            raise forms.ValidationError("email already exists")
        return email    

    def clean(self):
        data = self.cleaned_data
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('conf_password')

        if password2 != password:
            raise forms.ValidationError("passwords must match")
        return data    

loan_app/views.py
from django.shortcuts import redirect,render
from django.urls import reverse_lazy
from .decisionTables import *
from .forms import loginForm, registerForm
from django.contrib.auth import authenticate, login, get_user_model,logout
from .models import *
# Create your views here
import random
import string
import sys
import datetime

def get_random_string(length):
    # choose from all lowercase letter
    letters = string.ascii_lowercase
    result_str = ''.join(random.choice(letters) for i in range(length))
    return result_str


def apply(request):
  context={}
  return render(request, "apply.html",context);

def home(request):
  context={}
  return render(request, "home.html",context);

def bank_admin(request):
  context={}
  return render(request, "home_admin.html",context);


def details(request):
  context={}
  request.session["amount"]=request.POST['amount']
  request.session["term"]=request.POST['term']
  return render(request, "details.html",context);

def verification(request):
  request.session["age"]=request.POST['age']
  request.session["income"]=request.POST['income']
  request.session["properties"]=request.POST['properties']
  request.session["loans"]=request.POST['loans']
  request.session["credit"]=request.POST['credit']
  
  if 'job' in request.POST:
    #do somethings
    request.session["job"]=1
    print(True)
  else:
    print(False) 
    request.session["job"]=0
  context={}

  return render(request, "verification.html",context);


def getresult_admin(request):
  #machine learning results here.
  #----------------------------------------------
  #maximum amount can loan without taking into account credit score etc.
  reference_code=request.POST['reference']
  context={}
  if(Decision.objects.filter(refnum=reference_code).count()==0):
    return redirect("/bank_admin");
  else:
    decision_attached=Decision.objects.filter(refnum=reference_code)[0]
    print(decision_attached)
    customer_profile=CustomerProfile.objects.filter(user=decision_attached.user)[0]
    print(customer_profile)
    context["id"]=customer_profile.national_id;
    context["amount"]=decision_attached.amount
    context["decision"]=decision_attached.decision
    context["refnum"]=decision_attached.refnum
    context["user"] =decision_attached.user
    context["term_months"]=decision_attached.term_months
    context["first_name"]=decision_attached.user.first_name
    context["last_name"]=decision_attached.user.last_name


  maxEstd=predMaxamount( customer_profile.age, customer_profile.num_unsecured_l_term_all, customer_profile.num_loan_payments_missed, customer_profile.income, customer_profile.num_debit_orders_bounced)
  ###input is only 
  #whether customer defaults or not
  defaultFlag=predDefaultFlag( int(customer_profile.wknd_shopper_flag), int(customer_profile.salary_indicator), customer_profile.num_credit_transactions, customer_profile.house_credit_score, customer_profile.num_properties_owned)###input is 
  #final amount they can loan
  dAmount=decisionTable(customer_profile.age, customer_profile.income, customer_profile.house_credit_score, maxEstd, defaultFlag)
  print(dAmount)
  interest=6
  loandecision=None
  if(decision_attached.term_months>12):
    loandecision=lloanapprover(decision_attached.amount, decision_attached.term_months, customer_profile.income,defaultFlag)
    interest=12
  else:
    loandecision=sloanapprover(decision_attached.amount,dAmount)

  context["admin_suggestion"]=loandecision
  context["interest"]=interest
  total_interest=interestPM(decision_attached.amount,decision_attached.term_months,interest)*decision_attached.term_months
  context["monthly_repayment"]=monthlyrepayment(decision_attached.amount,total_interest,decision_attached.term_months,0)
  
  request.session["amount"]=decision_attached.amount
  request.session["full_name"]=decision_attached.user.first_name+" "+decision_attached.user.last_name
  
  return render(request, "getresult_admin.html",context);







def howitworks(request):
    context={}
    return render(request,"howitworks.html",context);

def terms(request):
    context={}
    return render(request,"terms.html",context);

def loan_agreement(request):
    context={}
    context["amount"]=request.session["amount"]
    context["full_name"]=request.session["full_name"]
    context["datetime"]=datetime.date.today().strftime("%B %d, %Y");
    return render(request,"loan_agreement.html",context);

def loan_tips(request):
    context={}
    return render(request,"loan_tips.html",context);

def getresult(request):
  #machine learning results here.
  #----------------------------------------------
  #maximum amount can loan without taking into account credit score etc.
  maxEstd=predMaxamount(int(request.session["age"]),int(request.session["loans"]),2,int(request.session["income"]),2)
  ###input is only 
  #whether customer defaults or not
  defaultFlag=predDefaultFlag(1,int(request.session["job"]),2,int(request.session["credit"]),int(request.session["properties"]))###input is 
  #final amount they can loan
  dAmount=decisionTable(int(request.session["age"]),int(request.session["income"]),int(request.session["credit"]),maxEstd,defaultFlag)

 
  loandecision=None
  if(int(request.session["term"])>12):
    loandecision=lloanapprover(int(request.session["amount"]),int(request.session["term"]),int(request.session["income"]),defaultFlag)
  else:
    loandecision=sloanapprover(int(request.session["amount"]),dAmount)
    
  print("max loan")
  print(maxEstd)
  print("will likely default?")
  print(defaultFlag)
  print("amount can loan given more vars")
  print(dAmount)
  print("loan  decision")
  print(loandecision);

#-------------------------------------------------------
  context={}
  context["amount"]=request.session["amount"]
  print(context["amount"])
  context["term"]=request.session["term"]
  print(context["term"]);
  context["age"]=request.session["age"]
  print(context["age"]);
  context["income"]=request.session["income"]
  print(context["income"]);
  context["properties"]=request.session["properties"]
  print(context["properties"]);
  context["loans"]=request.session["loans"]
  print(context["loans"]);
  context["credit"]=request.session["credit"]
  print(context["credit"]);
  context["job"]=request.session["job"]
  print(context["job"]);
  context["decision"]=loandecision
  print(context["decision"]);

  reference_code=get_random_string(13)

  context["ref_code"]=reference_code

  mydecision=Decision(user=request.user,decision=loandecision,refnum=reference_code,amount=request.session["amount"],term_months=request.session["term"])
  mydecision.save()
  print(mydecision);
  
  return render(request, "qualification.html",context);

  
def login_page(request):
    form = loginForm(request.POST or None)

    context = {
        "form" : form
    }

    print("user logged in")
    

    
    if form.is_valid():
        print(form.cleaned_data)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(request, username = username, password = password)
        print(request.user.is_authenticated)
        if user is not None:
            print(request.user.is_authenticated)
            login(request, user)
            context['form'] = loginForm()
            context["error"]=None
            return redirect("/")
        else:    
            # return invalid login
            context["error"]="Incorrect Username or Password"
            print("error")
    return render(request, "login.html",context)

def logout_request(request):
    logout(request)
    return redirect("/")
    
    
User = get_user_model()
def register_page(request):
    form = registerForm(request.POST or None)

    context = {
        "form" : form
    }

    if form.is_valid():
        print(form.cleaned_data)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        email = form.cleaned_data.get("email")
        first_name = form.cleaned_data.get("first_name")
        last_name = form.cleaned_data.get("last_name")
        new_user = User.objects.create_user(username,email,password)
        new_user.is_active = True
        new_user.first_name = first_name
        new_user.last_name = last_name
        new_user.save()
        print(new_user)
        return redirect("/login")
    return render(request, "register.html", context)

loan_app/templates/apply.html
{% extends 'base.html' %}

{% block content%}
{% load static %}

<script>
  function changebg(){
    document.body.style.background = "url({% static 'assets/img/agreement.jpg' %}) no-repeat center center fixed";
  }
  //changebg();
</script>

  <div class="homepage container">
      <div class="row text-left mt-5">
              
      <div class="right_col col-sm mt-5">
         
          <h1>Select your loan type and fill in the loan amount</h1>
           <form action="{%url 'loan_app:details'%}" method="post">
                {% csrf_token%}

                <br>
                <div class="finance_custom_input form-control input-group mb-3">
                  <div class="input-group-prepend">
                    <label class="input-group-text"for="inputGroupSelect01">Loan Type</label>
                  </div>
                  <select required class="custom-select" name="term" id="inputGroupSelect01">
                    <option value="3">Short Term: 3 Months</option>
                    <option value="6">Short Term: 6 Months</option>
                    <option value="12">Short Term: 12 Months</option>
                    <option value="60">Long Term: 5 Years</option>
                    <option value="120">Long Term: 10 Years</option>
										<option value="121">Long Term: 10+ Years</option>
                  </select>
                </div>


       

              
              <input required type="number" min="1000" name="amount" class="finance_custom_input form-control" placeholder="Enter your Amount" >
              <br>
            <button class="btn btn-warning btn-xl" type="submit">Next</button>
        </form>
          
      </div>

      </div>
      &nbsp;
  </div>

<!-- 

  <div class="col-lg-8 align-self-end">
      <h1 class="text-white font-weight-bold">Fill in the form!</h1>
      <hr class="divider" />
  </div>
  <div class="col-lg-8 align-self-baseline">
      
     
     
  </div> -->

{% endblock%}

loan_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>MrRobot Bank Loan Checker</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body style="font-family: Georgia, serif !important; background: url({% static 'assets/img/bg-masthead.jpg' %}) no-repeat center center fixed;">
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/">
                    <img src="{% static 'assets/img/logo.png' %}" width="250" height="40" class="d-inline-block align-top" alt="">
                  </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{%url 'loan_app:howitworks' %}">How It Works</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{%url 'loan_app:loan_tips' %}">Loan Tips</a></li>
                        <li id="auth">
                        
                          {% if user.is_authenticated %}
                          
                          
                          <li  class="nav-item nav-link active" >Hello {{ user.get_username }}</li>
                          <li class="nav-item"><a class="nav-link" href="{%url 'loan_app:logout_request' %}">Log out</a></li>
   
                          {% else %}
                          <li class="nav-item"><a class="nav-link" href="{%url 'loan_app:login_page' %}">Log In</a></li>
                          {% endif %}
                      </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        {% block content %} {% endblock %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
         <script src='https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js'></script>
    </body>

</html>

loan_app/templates/base_admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>MrRobot Bank Loan Checker</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        
    </head>
    <body style="font-family: Georgia, serif !important; background: url({% static 'assets/img/bg-masthead.jpg' %}) no-repeat center center fixed;">
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/">
                    <img src="{% static 'assets/img/logo.png' %}" width="250" height="40" class="d-inline-block align-top" alt="">
                  </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{%url 'loan_app:howitworks' %}">How It Works</a></li>

                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        {% block content %} {% endblock %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src='https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js'></script>
    </body>



</html>

loan_app/templates/details.html
{% extends 'base.html' %}

{% block content%}
{% load static %}


<script>
  function changebg(){
    document.body.style.background = "url({% static 'assets/img/sign.jpeg' %}) no-repeat center center fixed";
  }
 // changebg();
</script>

  <div class="homepage container">
      <div class="row text-left mt-5">
              
      <div class="col-sm mt-5">
          <h1>Step 2:</h1>
					<h1>Fill in the following required details</h1>
        
          <!-- <button class="home_call btn btn-warning"><a href="{%url 'loan_app:apply'%}">Check if you qualify</a></button> -->
      </div>
      <div class="right_col col-sm mt-5">
           <form action="{%url 'loan_app:verification'%}" method="post">
                {% csrf_token%}




                   <div class="row mb-3">
                      <label for="age_input" class="col-sm-6 col-form-label white">Verify Age:</label>
                      <div class="col-sm-6">
                          <input type="number" name="age" min="18" max="100" class="finance_custom_input form-control" id="age_input"  required>
                      </div>
                  </div>


                  <div class="row mb-3">
                      <label for="income_input" class="col-sm-6 col-form-label white">Monthly income: </label>
                      <div class="col-sm-6">
                          <input type="number" class="finance_custom_input form-control" id="income_input" name="income" required>
                      </div>
                  </div>

                  <div class="row mb-3">
                      <label for="properties_owned" class="col-sm-6 col-form-label white">Number of properties owned: </label>
                      <div class="col-sm-6">
                          <input type="number" min="0" class="finance_custom_input form-control" id="properties_owned" name="properties"  required>
                      </div>
                  </div>
                  <div class="row mb-3">
                      <label for="existing_loans" class="col-sm-6 col-form-label white">Number of unsecured long term loans: </label>
                      <div class="col-sm-6">
                          <input type="number" min="0" class="finance_custom_input form-control" id="existing_loans"  name="loans" required>
                      </div>
                  </div>
                  <div class="row mb-3">
                      <label for="credit_input" class="col-sm-6 col-form-label white">Your Credit Score: <a class="external_link" href="https://www.clearscore.com/za/">Get It Here</a></label>
                      <div class="col-sm-6">
                          <input type="number" min="0" max="999" name="credit" class="finance_custom_input form-control" id="credit_input"  required>
                      </div>
                  </div>

                  <div class="row mb-3">
                    <!-- <label for="salary_input" class="col-sm-6 col-form-label white">&nbsp;</label> -->
                    <div class="col-sm-6">
                        <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="" name="job" id="flexCheckChecked" unchecked>
                          <label class="form-check-label" for="flexCheckChecked">
                            I am currently employed
                          </label>
                        </div>
                      </div>
                  </div>
									
                  <!-- discuss with sunny -->


                  <div class="row">
                      <div class="col-sm-10 offset-sm-2">
                          <button type="submit" class="btn btn-warning">NEXT</button>
                      </div>
                  </div>
        </form>
          
      </div>

      </div>
      &nbsp;
  </div>
{% endblock%}

loan_app/templates/getresult_admin.html
{% extends 'base_admin.html' %}
{% load static %}
{% block content%}
  <div class="homepage_details container">
      <div class="row text-center mt-5">
              
      <div style="text-align: left;" class="col-sm mt-5">
          <h1>Details</h1>
					<br>
          <p class="lead">Identification Number:{{id}} </p>
          <p class="lead">First Name: {{first_name}}</p>
          <p class="lead">Surname: {{last_name}}</p>
          <p class="lead">Loan Amount: R{{amount}} </p>
          <p class="lead">Loan Term: {{term_months}} months</p>
          <p class="lead">Interest Rate: {{interest}}%</p>
          <p class="lead">Monthly Repayment: R{{monthly_repayment}} pm</p>


        {% if decision %}
          <p><i>Customer can be approved for the loan</i></p>
          
        {% else %}
          <p><i>Customer should not be approved for this loan:Risky Profile for amount</i></p>
          
        {% endif %}

					
          <!-- Button trigger modal -->

          <br><br>
           <a class="home_call approvedeny btn btn-warning" href="{%url 'loan_app:loan_agreement'%}">Approve</a>
          
          <a class="home_call approvedeny btn btn-warning" href="{%url 'loan_app:bank_admin'%}">Deny </a>
      </div>


			
      </div>
      
  </div>
    <br>
  <br>
  <br>
  <br>
  <br>

{% endblock%}

loan_app/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
  <div class="homepage container">
      <div class="row text-center mt-5">
              

      {% if user.is_authenticated and user.is_superuser %}
      <div class="col-sm mt-5">
        <h1>Welcome Administrator</h1>
        <br>
        <p class="lead">Click below to check customers profile and approve/deny loan requests</p>
        
        <a class="home_call btn btn-warning" href="{%url 'loan_app:bank_admin'%}">Go to bank admin</a>
      </div>
      
      {% else %}
      <div class="col-sm mt-5">
          <h1>Welcome To MrRobot Bank's Loan Checker</h1>
					<br>
          <p class="lead">Do you need a loan to follow your dreams?</p>
					
          <a class="home_call btn btn-warning" href="{%url 'loan_app:apply'%}">Check if I qualify</a>
      </div>
      {% endif %}
          
			
      </div>
      &nbsp;
  </div>
{% endblock%}

loan_app/templates/home_admin.html
{% extends 'base_admin.html' %}
{% load static %}
{% block content%}
  <div class="homepage container">
      <div class="row text-center mt-5">

          {% if user.is_authenticated and user.is_superuser %}
                               
          <div class="col-sm mt-5">
              <h1 style="color:orange">Bank Admin</h1>
              <br>
              <form action="{%url 'loan_app:getresult_admin'%}" method="post">
                    {% csrf_token%}
                  <input required type="text" name="reference" class="finance_custom_input form-control" placeholder=" Customer Reference Code" >

              <br>
              <button style="border-radius: 16px" class="home_call btn btn-warning " type="submit" >Check if Customer qualifies</button>
              </form>
          </div>
   
          {% else %}
                    <h3>Please Log In as admin</h3>
          {% endif %}
              


			
      </div>
      &nbsp;
  </div>
{% endblock%}

loan_app/templates/howitworks.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
  <div class="homepage_details container">
      <div class="row text-left mt-5">
              
      <div class="col-sm mt-5">
          <h1>How it works</h1>
					<br>
          <p class="lead"><b style="padding:10px;background-color: #000;color:white">1&nbsp;</b>&nbsp;we take all your personal information that you have provided us gracefully with don't worry its safe us!</p>
          <br><br>
          <p class="lead"><b style="padding:10px;background-color: #000;color:white">2&nbsp;</b>&nbsp;Use our sophisticated data processing techniques to evaluate your financial background.</p>
          <br><br>
          <p class="lead"><b style="padding:10px;background-color: #000;color:white">3&nbsp;</b>&nbsp;Poof!, our  system then  gives you an Answer.</p>
 
      </div>
			
      </div>
      &nbsp;
  </div>
{% endblock%}

loan_app/templates/login.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}

{% block content%}
<br>
<br>

 <div class="homepage container">
    <div class="row text-left mt-5">
      <div  class="box text-center">
        {% if error %}
        <p style="color:red;">{{error}}</p>
      {% endif %}
        <form class="form-signin" action="" method="post">
          <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
          <br>
          {% csrf_token %}
      
            {{ form.as_table }}
    <br>
          <button class="btn btn-lg btn-danger btn-block" type="submit">Sign in</button>
          <br><br>
        
          
          <!-- <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p> -->
          <br><br>
        </form>
      </div>
    </div>
  </div>
{% endblock%}

loan_app/templates/qualification.html
{% extends 'base.html' %}

{% block content%}
{% load static %}
  <script type="text/javascript">
    function openInNewTab() {
      window.open("{%url 'loan_app:terms'%}", '_blank').focus();
    }
  </script>

  <div class="homepage_details container">
      <div class="row text-left mt-5">
              
      <div class="col-sm mt-5">

        {% if decision %}
          <h1>Congratulations!</h1>
					<h1>You qualify for your R{{amount}} loan.</h1>
        {% else %}
          <h1>Unfortunately you dont qualify for this loan.!</h1>
					<h1>Try Improving Your credit score or increasing your income.</h1>
        {% endif %}
                  
        <h2>Here is your reference code:</h2>
        <div>
          <h3 class="twocol" name="ref_code" style="color:red"> {{ref_code}}</h3>
          <button class="twocol btn btn-warning" onclick="openInNewTab()">Have you read our T's & C's</button>  
        </div>
        
        <br>
        <h4>Please take note of the above reference code and visit your nearest Mr Robot Bank branch to finalise your loan if you qualified, or to enquire if you did not qualify</h4>


      </div>


      </div>
      &nbsp;
  </div>


{% endblock%}

loan_app/templates/verification.html
{% extends 'base.html' %}

{% block content%}
{% load static %}
<script>
  function changebg(){
    document.body.style.background = "url({% static 'assets/img/bg4_2.jpg' %}) no-repeat center center fixed";
  }
  ///changebg();
</script>


  <div class="homepage container">
      <div class="row text-left mt-5">
              
      <div class="col-sm mt-5">
          <h1>Step 3:</h1>
					<h1>Verify Your ID Number</h1>
          <!-- <button class="home_call btn btn-warning"><a href="{%url 'loan_app:apply'%}">Check if you qualify</a></button> -->
      </div>
      <div class="right_col col-sm mt-5">
           <form action="{%url 'loan_app:getresult'%}" method="post">
                {% csrf_token%}

              <input required type="text"  autocomplete="off" name="id_number" class="finance_custom_input form-control" maxlength="13" minlength="13" placeholder="Enter your ID number" >
              <br>
            <button class="btn btn-warning btn-xl" type="submit">Next</button>
        </form>
          
      </div>

      </div>
      &nbsp;
  </div>


{% endblock%}